### ISSUE TITLE
SkeletonCombinedRenderable.attachment_renderer_object is Some(null)

### ISSUE THREAD

**Issue by lenscas** [jabuwu/rusty_spine#16]
I am probably doing something wrong myself but I don't know where/when. I used the miniquad example as a base to create a node for my node system in macroquad.

Any pointers on what could cause it to be null would be appreciated as right now I am not sure what to look for.

**Comment by lenscas** [comment]
Figured it out. I was setting the callbacks too late.

Do note that the miniquad example does assume it is never `null` so some UB is happening if you do this but that is better left as its own issue.

**Comment by jabuwu** [comment]
> Do note that the miniquad example does assume it is never `null` so some UB is happening if you do this but that is better left as its own issue.

Can you elaborate on this more? I'm not sure what you're referring to. Thanks!

**Comment by jabuwu** [comment]
I see, I didn't put that message together with the title of this issue. It would make sense for `attachment_renderer_object` to become `None` if it encounters a null pointer, so I can make that change.

**Comment by lenscas** [comment]
> I see, I didn't put that message together with the title of this issue. It would make sense for `attachment_renderer_object` to become `None` if it encounters a null pointer, so I can make that change.

yea, sorry. TL;DR: `SkeletonCombinedRenderable.attachment_renderer_object`  is `null` if you forget to register the correct callbacks (or register them too late).  As the miniquad example doesn't do a nullcheck before using it this could lead to UB if the example is wrongly copied (like what I had).

It doesn't seem to be unsound luckily enough as you have to mess up inside an unsafe block to get the UB but some comment about it being possible to be null (and what it being null could mean) would be nice.

One thing that could be nice is if the `set_create_texture_cb` callbacks needs to be called but isn't setup yet that some kind of warning (or perhaps even panic) would be produced. I think that that would help the most when someone runs into this kind of issue.

Either that, or change the API such that you can not load a texture without having set the callback. This can be done by having the callback produce a Token that you must give to any function that could end up needing to call it. But that is obviously a big API change so not sure if that is ideal.

**Comment by jabuwu** [comment]
I made a PR from this feedback. #17 

The best solution is to remove the callbacks altogether, but unfortunately it's a result of how the underlying C code is written.

> One thing that could be nice is if the `set_create_texture_cb` callbacks needs to be called but isn't setup yet that some kind of warning (or perhaps even panic) would be produced.

I don't think it is ideal because `set_create_texture_cb` is not always necessary, like on a game server.

**Comment by lenscas** [comment]
> is not always necessary, like on a game server.

If a program doesn't need them then they can always have their `set_create_texture_cb` set to what is basically a noop, thus getting rid of the warnings.
