### ISSUE TITLE
Support files exported from Spine versions 4.2.0 and above

### ISSUE THREAD

**Issue by kumorig** [jabuwu/rusty_spine#25]
Hey, thanks for this lib and bevy_spine. super useful!

I updated the spine software to 4.2.06 and when re-exporting the same spines (with almost no changes), my app using bevy_spine stopped loading spines, no errors just failed silently displaying nothing where my spine assets were previously.

I put the issue in this repo because I think the actual problem is in this repo (only allowing "4.1*" versions), and probably here:
https://github.com/jabuwu/rusty_spine/blob/58d4421810215b0892ea9c9ccb7093ef3181bd19/src/c/spine_c.rs#L17921-L17924

Here is an example of exported json-file before and after:

before:
```
{
"skeleton": {
	"hash": "/fGfMFPfVdE",
	"spine": "4.1.24",
	"x": -221.36,
	"y": -97.78,
	"width": 446.78,
	"height": 652.25,
	"images": "C:/projects/my_project/assets/spine/images/",
	"audio": ""
},
"bones": ... (omitted the rest)
```
after:
```
{
"skeleton": {
	"hash": "Pga2cB0zv2k",
	"spine": "4.2.06",
	"x": -245.25,
	"y": -97.78,
	"width": 470.67,
	"height": 652.25,
	"images": "./images/",
	"audio": "C:/Users/someuser/Spine/examples/4.1/spineboy"
},
"bones": ... (omitted the rest)
```

* Just opening the the json file and changing the version back to `"spine": "4.1.24",` does make things work again, so there is a simple workaround. 
* I'm unable to load using bevy_spine's `SkeletonData::new_from_binary` at all.

Thanks for the help!

**Comment by jabuwu** [comment]
If you would like to help test, you can now try this branch: https://github.com/jabuwu/bevy_spine/pull/21

```
bevy_spine = { git = "https://github.com/jabuwu/bevy_spine", branch = "spine_4.2" }
```

**Comment by jabuwu** [comment]
This has been fixed in the latest releases
https://github.com/jabuwu/rusty_spine/releases/tag/0.8.0
https://github.com/jabuwu/bevy_spine/releases/tag/0.9.0
