### ISSUE TITLE
STATUS_ACCESS_VIOLATION on read skeleton with skin without attachments

### ISSUE THREAD

**Issue by lebedec** [jabuwu/rusty_spine#5]
Steps to reproduce:

1. Make and export any Spine project with skin without attachments
2. Read data via `SkeletonJson.read_skeleton_data_file`

Expected:  skeleton data read

Actual Result:
```
exit code: 0xc0000005, STATUS_ACCESS_VIOLATION
```

This error occurs probably because the "attachments" structure is incorrectly initialized (memory is allocated incorrectly), somewhere in `spSkeletonJson_readSkeletonDataFile`.

The problem is not critical, but important because there is a use case. For example, a skin that contains only bones for animation without attachments. 

Workaround: add one "fake" attachment which not affect your workflow, point for example

**Comment by jabuwu** [comment]
Thanks for reporting it! The issue is upstream and also affects the Spine C runtime. I've created an issue there.

https://github.com/EsotericSoftware/spine-runtimes/issues/2258

Another workaround is to use binary files instead of JSON, but I'll publish a new version soon after this is fixed.

**Comment by jabuwu** [comment]
I've published 0.5.1 with the fix for this crash
